---
label: Default
hide_body: true
fields:
- name: template
  type: text
  config:
    required: true
  label: template
  hidden: true
  default: default
- name: permalink
  type: text
  config:
    required: false
  label: permalink
  hidden: true
  default: "/:path/:basename/"
- name: title
  type: text
  config:
    required: true
  label: Title
  default: ''
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: Important for SEO
- name: sections
  type: blocks
  label: Sections
  template_types: []
  config:
    min: 
    max: 
pages:
- pages/work/inherited-weight.md
