---
label: Default
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: true
  label: layout
  hidden: true
  default: default
- name: permalink
  type: text
  config:
    required: false
  label: permalink
  hidden: true
  default: "/:path/:basename/"
- name: menu_image
  type: field_group
  config: {}
  fields:
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
  - name: alt_text
    type: text
    config:
      required: true
    label: Description (Alt Text)
    description: Required for accessibility.
  label: Menu Image
- name: page_image
  type: field_group_list
  fields:
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
  - name: alt_text
    type: text
    config:
      required: true
    label: Description (Alt Text)
  config:
    min: 
    max: 
    labelField: 
  label: Page image
- name: title
  type: text
  config:
    required: true
  label: Title
  default: ''
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: Important for SEO
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: YYYY
    time_format: 
    display_utc: false
pages:
- pages/work/inherited-weight.md
- pages/work/inherited-weight.md
