---
label: Default
hide_body: true
fields:
- name: template
  type: text
  config:
    required: true
  label: template
  hidden: true
  default: default
- name: permalink
  type: text
  config:
    required: false
  label: permalink
  hidden: true
  default: "/:path/:basename/"
- name: title
  type: text
  config:
    required: true
  label: Title
  default: ''
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: Important for SEO
- name: menu_image
  type: file
  config:
    maxSize: 64
  label: Menu image
  description: This image will be shown in the image menu on the home page.
- name: page_images
  type: field_group_list
  fields:
  - name: image
    type: file
    config:
      maxSize: 64
    label: image
  config:
    min: 
    max: 
    labelField: 
  label: Page Images
pages:
- pages/work/inherited-weight.md
- pages/work/inherited-weight.md
